#!/bin/bash

# Check if the number of arguments is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assigning arguments to variables
path_to_file="$1"
ip_address="$2"
username="$3"
path_to_ssh_key="$4"

# Transfer the file to the server's home directory using scp
scp -i "$path_to_ssh_key" -o StrictHostKeyChecking=no "$path_to_file" "${username}@${ip_address}:~/"

# Check the exit status of the scp command
if [ $? -eq 0 ]; then
    echo "File transferred successfully to ${username}@${ip_address}:~/"
else
    echo "File transfer failed."
fi

