#!/usr/bin/env bash
# Configure web-02 to be identical to web-01 and add a custom Nginx response header
var=$(hostname)
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" |sudo tee  /var/www/html/index.html
echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html
string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.twitter.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default
sudo service nginx restart
