#!/usr/bin/env bash
# Nginx nstallation from listening on port 80  with the minimum number of commands to automate your fix
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
